version: '3'

services:
  app:
    image: 'tmvdl/projects:yout'
    build: './src/app'
    volumes:
      - './src/app:/app'
      - './data:/data'
    ports:
      - '8080:80'

  googleapis:
    build: './src/googleapis/'
    volumes:
      - './src/googleapis/:/app'
      - './data:/data'
    tty: true
    stdin_open: true
